### ISSUE TITLE
infura is giving you 400 bad requests

### ISSUE THREAD

**Issue by vlashkari-pk** [dany-armstrong/zoo-nft-market-solana#1]
Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
zoo-nft-market-solana.surge.sh/:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
zoo-nft-market-solana.surge.sh/:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
zoo-nft-market-solana.surge.sh/:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
zoo-nft-market-solana.surge.sh/:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
zoo-nft-market-solana.surge.sh/:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
VM13:1          POST https://ipfs.infura.io:5001/api/v0/add?stream-channels=true&progress=false 401 (Unauthorized)
(anonymous) @ VM13:1
fetch @ fetch.browser.js:106
(anonymous) @ http.js:129
d @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
t @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ http.js:91
e.fetch @ core.js:132
value @ http.js:171
(anonymous) @ add-all.js:17
f @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
r @ AsyncGenerator.js:26
(anonymous) @ AsyncGenerator.js:31
Promise.then (async)
r @ AsyncGenerator.js:29
(anonymous) @ AsyncGenerator.js:19
_invoke @ AsyncGenerator.js:6
$N.next @ AsyncGenerator.js:86
(anonymous) @ index.js:10
d @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
t @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ index.js:10
(anonymous) @ add.js:9
f @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
e @ add.js:7
(anonymous) @ add.js:7
(anonymous) @ Mint.ts:47
f @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Mint.ts:44
(anonymous) @ Minter.js:81
f @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Minter.js:67
onFinish @ Form.js:75
(anonymous) @ useForm.js:931
Promise.then (async)
Ie.submit @ useForm.js:926
onSubmit @ Form.js:132
Te @ react-dom.production.min.js:54
ze @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
jr @ react-dom.production.min.js:105
Lr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
sc @ react-dom.production.min.js:273
Ne @ react-dom.production.min.js:52
Hr @ react-dom.production.min.js:109
Yt @ react-dom.production.min.js:74
Vt @ react-dom.production.min.js:73
Show 32 more frames
core.js:75 Uncaught (in promise) HTTPError: project id required

    at core.js:75:15
    at f (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at r (asyncToGenerator.js:3:20)
    at u (asyncToGenerator.js:25:9)

**Comment by vlashkari-pk** [comment]
https://docs.infura.io/infura/networks/ipfs/how-to/make-requests This will be useful you have to authorize the request now
